# Dataset ALLFLOWMETER_HIKARI2021

In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
#import seaborn as sns
from scipy import stats
from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression

# Carregamento e limpeza do dataset
df = pd.read_csv("../../data/raw/ALLFLOWMETER_HIKARI2021.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,uid,originh,originp,responh,responp,flow_duration,fwd_pkts_tot,bwd_pkts_tot,...,idle.min,idle.max,idle.tot,idle.avg,idle.std,fwd_init_window_size,bwd_init_window_size,fwd_last_window_size,traffic_category,Label
0,0,0,Cg61Jch3vdz9DBptj,103.255.15.23,13316,128.199.242.104,443,2.207588,15,14,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,29200,65160,0,Bruteforce-XML,1
1,1,1,CdRIlqLWdj35Y9vW9,103.255.15.23,13318,128.199.242.104,443,15.624266,15,14,...,1.534300e+07,1.534300e+07,1.534300e+07,1.534300e+07,0.0,29200,65160,0,Bruteforce-XML,1
2,2,2,CLzp9Khd0Y09Qkgrg,103.255.15.23,13320,128.199.242.104,443,12.203357,14,13,...,1.196814e+07,1.196814e+07,1.196814e+07,1.196814e+07,0.0,29200,65160,0,Bruteforce-XML,1
3,3,3,Cnf1YA4iLB4CSNWB88,103.255.15.23,13322,128.199.242.104,443,9.992448,14,13,...,9.759205e+06,9.759205e+06,9.759205e+06,9.759205e+06,0.0,29200,65160,0,Bruteforce-XML,1
4,4,4,C4ZKvv3fpO72EAOsJ6,103.255.15.23,13324,128.199.242.104,443,7.780611,14,14,...,7.545305e+06,7.545305e+06,7.545305e+06,7.545305e+06,0.0,29200,65160,0,Bruteforce-XML,1

inspect the dataset

In [32]:
df.shape
df.info()
df.columns.tolist()
df.isna().sum().sort_values(ascending=False).head(20)
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 555278 entries, 0 to 555277
Data columns (total 88 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Unnamed: 0.1              555278 non-null  int64
 1   Unnamed: 0                555278 non-null  int64
 2   uid                       555278 non-null  str
 3   originh                   555278 non-null  str
 4   originp                   555278 non-null  int64
 5   responh                   555278 non-null  str
 6   responp                   555278 non-null  int64
 7   flow_duration             555278 non-null  float64
 8   fwd_pkts_tot              555278 non-null  int64
 9   bwd_pkts_tot              555278 non-null  int64
 10  fwd_data_pkts_tot         555278 non-null  int64
 11  bwd_data_pkts_tot         555278 non-null  int64
 12  fwd_pkts_per_sec          555278 non-null  float64
 13  bwd_pkts_per_sec          555278 non-null  float64
 14  flow_pkts_per_sec         555278 non-null  float64
 15  down_up_ratio             555278 non-null  float64
 16  fwd_header_size_tot       555278 non-null  int64
 17  fwd_header_size_min       555278 non-null  int64
 18  fwd_header_size_max       555278 non-null  int64
 19  bwd_header_size_tot       555278 non-null  int64
 20  bwd_header_size_min       555278 non-null  int64
 21  bwd_header_size_max       555278 non-null  int64
 22  flow_FIN_flag_count       555278 non-null  int64
 23  flow_SYN_flag_count       555278 non-null  int64
 24  flow_RST_flag_count       555278 non-null  int64
 25  fwd_PSH_flag_count        555278 non-null  int64
 26  bwd_PSH_flag_count        555278 non-null  int64
 27  flow_ACK_flag_count       555278 non-null  int64
 28  fwd_URG_flag_count        555278 non-null  int64
 29  bwd_URG_flag_count        555278 non-null  int64
 30  flow_CWR_flag_count       555278 non-null  int64
 31  flow_ECE_flag_count       555278 non-null  int64
 32  fwd_pkts_payload.min      555278 non-null  float64
 33  fwd_pkts_payload.max      555278 non-null  float64
 34  fwd_pkts_payload.tot      555278 non-null  float64
 35  fwd_pkts_payload.avg      555278 non-null  float64
 36  fwd_pkts_payload.std      555278 non-null  float64
 37  bwd_pkts_payload.min      555278 non-null  float64
 38  bwd_pkts_payload.max      555278 non-null  float64
 39  bwd_pkts_payload.tot      555278 non-null  float64
 40  bwd_pkts_payload.avg      555278 non-null  float64
 41  bwd_pkts_payload.std      555278 non-null  float64
 42  flow_pkts_payload.min     555278 non-null  float64
 43  flow_pkts_payload.max     555278 non-null  float64
 44  flow_pkts_payload.tot     555278 non-null  float64
 45  flow_pkts_payload.avg     555278 non-null  float64
 46  flow_pkts_payload.std     555278 non-null  float64
 47  fwd_iat.min               555278 non-null  float64
 48  fwd_iat.max               555278 non-null  float64
 49  fwd_iat.tot               555278 non-null  float64
 50  fwd_iat.avg               555278 non-null  float64
 51  fwd_iat.std               555278 non-null  float64
 52  bwd_iat.min               555278 non-null  float64
 53  bwd_iat.max               555278 non-null  float64
 54  bwd_iat.tot               555278 non-null  float64
 55  bwd_iat.avg               555278 non-null  float64
 56  bwd_iat.std               555278 non-null  float64
 57  flow_iat.min              555278 non-null  float64
 58  flow_iat.max              555278 non-null  float64
 59  flow_iat.tot              555278 non-null  float64
 60  flow_iat.avg              555278 non-null  float64
 61  flow_iat.std              555278 non-null  float64
 62  payload_bytes_per_second  555278 non-null  float64
 63  fwd_subflow_pkts          555278 non-null  float64
 64  bwd_subflow_pkts          555278 non-null  float64
 65  fwd_subflow_bytes         555278 non-null  float64
 66  bwd_subflow_bytes         555278 non-null  float64
 67  fwd_bulk_bytes            555278 non-null  float64
 68  bwd_bulk_bytes            555278 non-null  float64
 69  fwd_bulk_packets          555278 non-null  float64
 70  bwd_bulk_packets          555278 non-null  float64
 71  fwd_bulk_rate             555278 non-null  float64
 72  bwd_bulk_rate             555278 non-null  float64
 73  active.min                555278 non-null  float64
 74  active.max                555278 non-null  float64
 75  active.tot                555278 non-null  float64
 76  active.avg                555278 non-null  float64
 77  active.std                555278 non-null  float64
 78  idle.min                  555278 non-null  float64
 79  idle.max                  555278 non-null  float64
 80  idle.tot                  555278 non-null  float64
 81  idle.avg                  555278 non-null  float64
 82  idle.std                  555278 non-null  float64
 83  fwd_init_window_size      555278 non-null  int64
 84  bwd_init_window_size      555278 non-null  int64
 85  fwd_last_window_size      555278 non-null  int64
 86  traffic_category          555278 non-null  str
 87  Label                     555278 non-null  int64
dtypes: float64(56), int64(28), str(4)
memory usage: 372.8 MB

np.int64(0)

Find the label columns

In [33]:
for col in df.columns:
    print(col, df[col].nunique(), df[col].dropna().unique()[:10])

Unnamed: 0.1 555278 [0 1 2 3 4 5 6 7 8 9]
Unnamed: 0 350710 [0 1 2 3 4 5 6 7 8 9]
uid 555278 <StringArray>
[ 'Cg61Jch3vdz9DBptj',  'CdRIlqLWdj35Y9vW9',  'CLzp9Khd0Y09Qkgrg',
 'Cnf1YA4iLB4CSNWB88', 'C4ZKvv3fpO72EAOsJ6',  'CyC8D5X7IIG7U95l4',
 'CEXyM013OxRuUddrS2', 'CVFc4q26WLSGblwO2c', 'CCvZhO2f7ztLs9Hopc',
  'CIPZU1mfhrkqqix49']
Length: 10, dtype: str
originh 2899 <StringArray>
[            '103.255.15.23',             '103.255.15.27',
             '103.255.15.20',                   '0.0.0.0',
            '202.169.224.77',             '103.255.15.40',
            '103.255.15.206', 'fe80::c1a7:7791:969e:3c06',
             '103.255.15.21',             '103.255.15.65']
Length: 10, dtype: str
originp 62886 [13316 13318 13320 13322 13324 13326 13328 13330 13332 13334]
responh 7991 <StringArray>
[   '128.199.242.104',      '128.199.88.81',      '103.255.15.23',
     '103.255.15.255',    '255.255.255.255',            '8.8.8.8',
      '34.107.221.82', '2600:1901:0:38d7::',       '54.230.151.7',
       '54.230.151.5']
Length: 10, dtype: str
responp 4557 [  443 42000 42001  1947    53    67  5678    80 10670   137]
flow_duration 193558 [ 2.207588 15.624266 12.203357  9.992448  7.780611  4.571433  2.19264
 16.082514 13.87324  11.331464]
fwd_pkts_tot 1448 [ 15  14  13  16  10  11 230  21 187  32]
bwd_pkts_tot 1522 [ 14  13  12  15  11  16  10 222  17 182]
fwd_data_pkts_tot 607 [ 6  7  5  4 10  9  8  3 16  0]
bwd_data_pkts_tot 1454 [  6   5   4   7 217  14 179  24   9  16]
fwd_pkts_per_sec 210316 [6.794746 0.960045 1.147225 1.401058 1.799345 3.062497 6.384997 0.870511
 1.081218 1.235498]
bwd_pkts_per_sec 207066 [6.341763 0.896042 1.065281 1.300983 1.799345 2.843747 5.928926 0.870511
 1.009137 1.147248]
flow_pkts_per_sec 215151 [13.136509  1.856087  2.212506  2.702041  3.598689  5.906244 12.313923
  1.741021  2.090355  2.382746]
down_up_ratio 7868 [0.933333 0.928571 1.       0.857143 0.866667 0.923077 0.875    0.785714
 1.066667 0.846154]
fwd_header_size_tot 5369 [464 488 432 476 472 468 400 444 412 516]
fwd_header_size_min 9 [20 32 40  8  0 28 24 36 44]
fwd_header_size_max 13 [40 44 52 60 32  8 48 20 56  0]
bwd_header_size_tot 3566 [492 468 448 436 480 424 456 392 488 512]
bwd_header_size_min 8 [32  0 20  8 40 24 36 28]
bwd_header_size_max 13 [44 40  0 20  8 32 56 52 28 36]
flow_FIN_flag_count 15 [ 2  1  0  3  4  5  7  6 12  8]
flow_SYN_flag_count 19 [ 2  3  0  4  1  5 23 22 16  9]
flow_RST_flag_count 46 [ 2  1  4  3  0  5  7  6 13 11]
fwd_PSH_flag_count 572 [ 6  7  5  4 10  9  8  3 16  0]
bwd_PSH_flag_count 1034 [ 5  4  3  6  7 14 10 12  9  8]
flow_ACK_flag_count 2395 [26 24 25 23 27 22 28 19 21 20]
fwd_URG_flag_count 5 [0 1 4 2 3]
bwd_URG_flag_count 2 [0 1]
flow_CWR_flag_count 5 [0 1 2 3 4]
flow_ECE_flag_count 3 [0 2 1]
fwd_pkts_payload.min 175 [  0.  40.  41. 300. 130. 127. 124.  42.  29.  55.]
fwd_pkts_payload.max 1921 [742. 745. 744. 741. 746. 747. 748. 743. 749. 750.]
fwd_pkts_payload.tot 10759 [1826. 1829. 1828. 1825. 1830. 1831. 1832. 1827. 1833. 1834.]
fwd_pkts_payload.avg 31166 [121.733333 121.933333 130.571429 130.428571 130.357143 122.
 130.642857 121.866667 130.714286 130.785714]
fwd_pkts_payload.std 46892 [220.736581 221.339257 226.803444 226.387589 226.179849 221.540387
 227.011558 221.138246 227.219795 227.428156]
bwd_pkts_payload.min 303 [  0.  57. 153.  77. 119. 157. 181. 163.  97. 146.]
bwd_pkts_payload.max 5196 [ 1448.  2896.  4096.  8688.  4344. 11584.  5634. 17598.  5792.  6001.]
bwd_pkts_payload.tot 28467 [  5025.   5001.   4948.   6624.   6416.   5826. 484987.  18140. 420706.
  43300.]
bwd_pkts_payload.avg 46694 [358.928571 386.538462 418.75     335.       384.692308 380.615385
 416.75     353.428571 456.818182 314.0625  ]
bwd_pkts_payload.std 58631 [552.23984  817.479013 792.173394 845.168098 540.161087 565.964425
 817.267657 846.214901 564.642603 551.656905]
flow_pkts_payload.min 179 [  0.  40.  41. 300. 130. 127. 124.  42.  29.  55.]
flow_pkts_payload.max 5378 [ 1448.  2896.  4096.  8688.  4344. 11584.  5634. 17598.  5792.  6001.]
flow_pkts_payload.tot 31764 [6851. 6854. 6853. 6850. 6855. 6856. 6857. 6852. 6858. 6859.]
flow_pkts_payload.avg 53923 [236.241379 236.344828 253.814815 244.75     253.740741 244.642857
 236.37931  253.703704 253.851852 236.310345]
flow_pkts_payload.std 64994 [424.859275 424.987166 592.570284 583.468215 592.506773 583.373409
 425.02995  592.475109 592.60213  424.944459]
fwd_iat.min 24719 [18.119812 20.980835 36.001205 50.067902 16.927719 26.941299 33.140182
 32.186508 20.027161 25.987625]
fwd_iat.max 153769 [ 1963762.044907 15343001.127243 11968142.986298  9759204.864502
  7545305.013657  4340378.99971   1964499.950409 15848376.03569
 13593590.974808 11094823.83728 ]
fwd_iat.tot 174511 [ 2207602.977753 15624277.114868 12203381.061554  9992470.026016
  7780620.098114  4571445.941925  2192651.987076 16082529.067993
 13873255.01442  11331480.026245]
fwd_iat.avg 180120 [ 157685.926982 1116019.793919  938721.62012   768651.540463
  598509.238316  351649.68784   168665.537467 1237117.620615
  990946.786744  871652.309711]
fwd_iat.std 172634 [ 520505.22679  4094889.239622 3314031.527574 2701448.225785
 2087417.478288 1198738.719977  540182.137485 4390212.34557
 3627383.922173 3071792.095169]
bwd_iat.min 25000 [ 7.867813 20.980835 15.02037   6.914139  8.106232 27.894974 15.974045
 19.073486 26.941299 10.967255]
bwd_iat.max 148218 [ 2032928.943634 15411444.187164 12036739.110947  9828446.865082
  7613718.986511  4409031.867981  2032080.173492 15916583.776474
 13661505.937576 11162833.929062]
bwd_iat.tot 165961 [ 2177949.905396 15595169.067383 12174822.092056  9963347.911835
  7750840.902328  4542500.019073  2163109.064102 16052683.115005
 13844882.965088 11301831.960678]
bwd_iat.avg 178145 [ 167534.608107 1199628.389799 1014568.507671  830278.992653
  596218.530948  378541.668256  180259.088675 1234821.778077
 1064990.997314  941819.330057]
bwd_iat.std 166355 [ 560626.711841 4270147.597061 3471106.619308 2833716.489897
 2108534.388721 1269338.854547  583304.678307 4411338.872877
 3784813.618833 3218809.752961]
flow_iat.min 25731 [ 7.867813 10.01358  15.02037  20.980835  9.059906  6.914139  8.106232
 10.967255 18.835068  5.960464]
flow_iat.max 169616 [ 1963762.044907 15343001.127243 11968142.986298  9759204.864502
  7545305.013657  4340378.99971   1964499.950409 15848376.03569
 13593590.974808 11094823.83728 ]
flow_iat.tot 207673 [ 2207602.977753 15624277.114868 12203381.061554  9992470.026016
  7780620.098114  4571445.941925  2192651.987076 16082529.067993
 13873255.01442  11331480.026245]
flow_iat.avg 225984 [ 78842.963491 558009.89696  469360.81006  384325.770231 288171.114745
 175824.84392   84332.768734 595649.22474  495473.393372 435826.154856]
flow_iat.std 312471 [ 369637.838843 2897622.376458 2345336.024887 1912151.636283
 1450410.620644  849505.700548  383696.754871 3048315.275349
 2567030.513596 2174055.898552]
payload_bytes_per_second 282840 [3103.387105  438.676603  561.566789  685.81794   880.779153 1498.654854
 3124.543835  425.928433  494.116731  604.511471]
fwd_subflow_pkts 3750 [ 7.5       7.        5.       13.        6.5      14.        5.333333
  8.        5.5       4.666667]
bwd_subflow_pkts 3908 [ 7.        6.5       6.        4.333333  7.5      13.       14.
  4.666667  5.5       8.      ]
fwd_subflow_bytes 16017 [913.       914.5      914.       912.5      915.       915.5
 916.       610.666667 913.5      916.5     ]
bwd_subflow_bytes 34837 [  2512.5   1675.    2500.5   4948.    3312.    3208.    2913.    1667.
 242493.5   9070. ]
fwd_bulk_bytes 1391 [   0.       2395.       1108.        100.        400.        600.
  800.       2436.       1301.333333 3458.      ]
bwd_bulk_bytes 16827 [     0.       157028.666667 403562.        34698.        14104.
  33762.       219130.        36173.       403563.        14089.      ]
fwd_bulk_packets 209 [ 0.       13.5       6.        5.        8.       12.       16.
  9.966667 11.        7.545455]
bwd_bulk_packets 3463 [  0.   69.  168.   14.    7.    6.   87.5   8.  122.    9. ]
fwd_bulk_rate 2150 [0.00000000e+00 9.36800233e+03 3.52983220e+03 6.66296210e+01
 1.04614274e+03 4.05530961e+02 5.10039489e+02 5.23052289e+02
 3.78735521e+02 1.01006719e+06]
bwd_bulk_rate 33952 [      0.        101397.410098  127838.302667  120482.513161
   44421.897803  772480.807174   97478.537439  415786.677424
  144141.37884  1159187.564396]
active.min 179877 [2207602.977753   28837.919235   28913.021088   29529.094696
   28550.14801  4571445.941925 2192651.987076   28995.990753
   28571.128845   28536.081314]
active.max 198319 [2207602.977753  252438.06839   206325.054169  203736.066818
  206764.936447 4571445.941925 2192651.987076  205157.04155
  251092.910767  208120.107651]
active.tot 198782 [2207602.977753  281275.987625  235238.075256  233265.161514
  235315.084457 4571445.941925 2192651.987076  234153.032303
  279664.039612  236656.188965]
active.avg 200069 [2207602.977753  140637.993813  117619.037628  116632.580757
  117657.542229 4571445.941925 2192651.987076  117076.516151
  139832.019806  118328.094482]
active.std 36488 [     0.       158109.181742 125449.251656 123182.931318 126016.885411
 124564.673599 157346.660958 126985.082815 124040.703978 131219.998154]
idle.min 43170 [       0.       15343001.127243 11968142.986298  9759204.864502
  7545305.013657 15848376.03569  13593590.974808 11094823.83728
  8884035.110474  6664245.128632]
idle.max 42770 [       0.       15343001.127243 11968142.986298  9759204.864502
  7545305.013657 15848376.03569  13593590.974808 11094823.83728
  8884035.110474  6664245.128632]
idle.tot 44664 [       0.       15343001.127243 11968142.986298  9759204.864502
  7545305.013657 15848376.03569  13593590.974808 11094823.83728
  8884035.110474  6664245.128632]
idle.avg 44438 [       0.       15343001.127243 11968142.986298  9759204.864502
  7545305.013657 15848376.03569  13593590.974808 11094823.83728
  8884035.110474  6664245.128632]
idle.std 18164 [       0.       12285040.369242 12007824.34325  12152948.170717
 12659137.968463 12172599.717304 12254488.934019 12061236.869584
 11969660.325786 11946714.126603]
fwd_init_window_size 515 [29200   288   268     0 28800    85  1024 65535  8192 64216]
bwd_init_window_size 185 [65160 28960     0 65535 26847 14600 56940   131  1000 29200]
fwd_last_window_size 3461 [  0  96  97 288 119 268 243 269 179 221]
traffic_category 6 <StringArray>
[     'Bruteforce-XML',          'Bruteforce',          'Background',
              'Benign',             'Probing', 'XMRIGCC CryptoMiner']
Length: 6, dtype: str
Label 2 [1 0]

Check class balance

In [34]:
df["Label"].value_counts()
df["Label"].value_counts(normalize=True) * 100

Label
0    93.211328
1     6.788672
Name: proportion, dtype: float64

In [35]:
df["traffic_category"].value_counts()
df["traffic_category"].value_counts(normalize=True) * 100

traffic_category
Benign                 62.568839
Background             30.642489
Probing                 4.211944
Bruteforce              1.059649
Bruteforce-XML          0.926563
XMRIGCC CryptoMiner     0.590515
Name: proportion, dtype: float64

In [36]:
df.columns[df.columns.str.contains("category|label|traffic", case=False)]
pd.crosstab(df["traffic_category"], df["Label"])

Label                     0      1
traffic_category
Background           170151      0
Benign               347431      0
Bruteforce                0   5884
Bruteforce-XML            0   5145
Probing                   0  23388
XMRIGCC CryptoMiner       0   3279

quick dataset summary

In [37]:
summary = {
    "rows": df.shape[0],
    "columns": df.shape[1],
    "duplicates": int(df.duplicated().sum()),
    "missing_values_total": int(df.isna().sum().sum())
}

summary

{'rows': 555278, 'columns': 88, 'duplicates': 0, 'missing_values_total': 0}

**Create X and y**

In [38]:
target_col = "Label"

drop_cols = [
    "Unnamed: 0.1",
    "Unnamed: 0",
    "uid",
    "originh",
    "responh",
    "traffic_category",
    "Label"
]

X = df.drop(columns=drop_cols, errors="ignore")
y = df[target_col]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (555278, 81)
y shape: (555278,)

Cleaning values

In [39]:
X = X.select_dtypes(include=["number"])

print("Final X shape:", X.shape)
print("Columns used:", X.columns.tolist())

#Clean missing or infinite values
X = X.replace([np.inf, -np.inf], np.nan)
print("Missing values before cleaning:", X.isna().sum().sum())
X = X.fillna(X.median(numeric_only=True))
print("Missing values after cleaning:", X.isna().sum().sum())

Final X shape: (555278, 81)
Columns used: ['originp', 'responp', 'flow_duration', 'fwd_pkts_tot', 'bwd_pkts_tot', 'fwd_data_pkts_tot', 'bwd_data_pkts_tot', 'fwd_pkts_per_sec', 'bwd_pkts_per_sec', 'flow_pkts_per_sec', 'down_up_ratio', 'fwd_header_size_tot', 'fwd_header_size_min', 'fwd_header_size_max', 'bwd_header_size_tot', 'bwd_header_size_min', 'bwd_header_size_max', 'flow_FIN_flag_count', 'flow_SYN_flag_count', 'flow_RST_flag_count', 'fwd_PSH_flag_count', 'bwd_PSH_flag_count', 'flow_ACK_flag_count', 'fwd_URG_flag_count', 'bwd_URG_flag_count', 'flow_CWR_flag_count', 'flow_ECE_flag_count', 'fwd_pkts_payload.min', 'fwd_pkts_payload.max', 'fwd_pkts_payload.tot', 'fwd_pkts_payload.avg', 'fwd_pkts_payload.std', 'bwd_pkts_payload.min', 'bwd_pkts_payload.max', 'bwd_pkts_payload.tot', 'bwd_pkts_payload.avg', 'bwd_pkts_payload.std', 'flow_pkts_payload.min', 'flow_pkts_payload.max', 'flow_pkts_payload.tot', 'flow_pkts_payload.avg', 'flow_pkts_payload.std', 'fwd_iat.min', 'fwd_iat.max', 'fwd_iat.tot', 'fwd_iat.avg', 'fwd_iat.std', 'bwd_iat.min', 'bwd_iat.max', 'bwd_iat.tot', 'bwd_iat.avg', 'bwd_iat.std', 'flow_iat.min', 'flow_iat.max', 'flow_iat.tot', 'flow_iat.avg', 'flow_iat.std', 'payload_bytes_per_second', 'fwd_subflow_pkts', 'bwd_subflow_pkts', 'fwd_subflow_bytes', 'bwd_subflow_bytes', 'fwd_bulk_bytes', 'bwd_bulk_bytes', 'fwd_bulk_packets', 'bwd_bulk_packets', 'fwd_bulk_rate', 'bwd_bulk_rate', 'active.min', 'active.max', 'active.tot', 'active.avg', 'active.std', 'idle.min', 'idle.max', 'idle.tot', 'idle.avg', 'idle.std', 'fwd_init_window_size', 'bwd_init_window_size', 'fwd_last_window_size']
Missing values before cleaning: 0
Missing values after cleaning: 0

# Split and train (70/30%)

In [47]:
#Train/test split 30% test size, stratified by the target variable
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30, #test size of 30%
    random_state=42,
    stratify=y
)

print("Training:", X_train.shape)
print("Testing:", X_test.shape)

Training: (388694, 81)
Testing: (166584, 81)

# Scale the data for Logistic Regression

In [48]:
from sklearn.preprocessing import StandardScaler
#Some models need scaling. Logistic Regression performs better when features are on comparable scales.
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Model 1 — Logistic Regression

In [49]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(
    max_iter=1000,
    random_state=42,
    class_weight="balanced"
)

log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)

# Train Model 2 — Random Forest

In [50]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

# Evaluate both models

In [51]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix

def evaluate_model(model_name, y_true, y_pred):
    results = {
        "Model": model_name,
        "Accuracy": accuracy_score(y_true, y_pred),
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "F1-score": f1_score(y_true, y_pred, zero_division=0)
    }
    
    print(f"\n=== {model_name} ===")
    print(classification_report(y_true, y_pred, zero_division=0))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    
    return results

# Evaluation

In [52]:
results_log = evaluate_model("Logistic Regression", y_test, y_pred_log)
results_rf = evaluate_model("Random Forest", y_test, y_pred_rf)

=== Logistic Regression ===
              precision    recall  f1-score   support

           0       1.00      0.83      0.91    155275
           1       0.30      0.99      0.46     11309

    accuracy                           0.84    166584
   macro avg       0.65      0.91      0.68    166584
weighted avg       0.95      0.84      0.88    166584

Confusion Matrix:
[[129008  26267]
 [    92  11217]]

=== Random Forest ===
              precision    recall  f1-score   support

           0       0.95      0.91      0.93    155275
           1       0.24      0.38      0.29     11309

    accuracy                           0.88    166584
   macro avg       0.60      0.65      0.61    166584
weighted avg       0.90      0.88      0.89    166584

Confusion Matrix:
[[141689  13586]
 [  7028   4281]]